### ISSUE TITLE
Typo in function glcf description

### ISSUE THREAD

**Issue by stefanofari** [andreasvarga/DescriptorSystemTools#2]
I was checking `glcf`, and I noticed a typo that in the readme the initial description. In particular, equation

```
                                               -1
                G(lambda) = N(lambda)*M(lambda)   ,
```

seem to have inverted multiplication (and consequent superscript).

**Comment by andreasvarga** [comment]
Thanks for raising this issue. I corrected `glcf` (and also `glcfid`).
